In [39]:
%pip install tabula-py

Requirement already satisfied: tabula-py in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (2.9.0)
Requirement already satisfied: pandas>=0.25.3 in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from tabula-py) (1.26.4)
Requirement already satisfied: distro in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\gustavo losch\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
import tabula

In [41]:
tabela = tabula.read_pdf("Extrato Cecilia.pdf", pages="all")[0]

tabela

c:\Users\Gustavo Losch\AppData\Local\Programs\Python\Python312\Lib\site-packages\tabula\io.py:1045: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[c] = pd.to_numeric(df[c], errors="ignore")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,RDA DESIGN,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,RDA DESIGN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,08/05/2024,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,EXTRATO DO CLIENTE,Período de: 01/01/2000,à,NaN,30/05/2024
3,ÓDIGO::,95 - CECILIA MASOUD,NaN,NaN,NaN,NaN,NaN,NaN
4,DOCTO:,HISTÓRICO,VENCIMENTO:,VALOR: R$ DESC.: R$ ACRESC:,VALOR REC: RECEBIDO EM:,NaN,NaN,R$ DEVIDO:
5,OS-7167,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
6,OS-7227,FECHAMENTO O.S. À PRAZO,08/01/2024,"100,00 0,00 0,00","0,00",/ /,NaN,"100,00"
7,OS-7055,FECHAMENTO O.S. À PRAZO,08/01/2024,"350,00 0,00 0,00","0,00",/ /,NaN,"350,00"
8,OS-7213,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
9,OS-7211,FECHAMENTO O.S. À PRAZO,08/01/2024,"80,00 0,00 0,00","0,00",/ /,NaN,"80,00"
10,OS-7209,FECHAMENTO O.S. À PRAZO,08/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
11,OS-7166,FECHAMENTO O.S. À PRAZO,08/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
12,OS-7168,FECHAMENTO O.S. À PRAZO,08/01/2024,"300,00 0,00 0,00","0,00",/ /,NaN,"300,00"
13,OS-7142,FECHAMENTO O.S. À PRAZO,08/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
14,OS-7222,FECHAMENTO O.S. À PRAZO,08/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
15,OS-7117,FECHAMENTO O.S. À PRAZO,08/01/2024,"400,00 0,00 0,00","0,00",/ /,NaN,"400,00"
16,OS-7141,FECHAMENTO O.S. À PRAZO,08/01/2024,"2.800,00 0,00 0,00","0,00",/ /,NaN,"2.800,00"
17,OS-7188,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
18,OS-7054,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
19,OS-7092,FECHAMENTO O.S. À PRAZO,10/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
20,OS-7116,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
21,OS-7118,FECHAMENTO O.S. À PRAZO,10/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
22,OS-7119,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
23,OS-7134,FECHAMENTO O.S. À PRAZO,10/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
24,OS-7135,FECHAMENTO O.S. À PRAZO,10/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
25,OS-7255,FECHAMENTO O.S. À PRAZO,15/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
26,OS-7254,FECHAMENTO O.S. À PRAZO,15/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
27,OS-7260,FECHAMENTO O.S. À PRAZO,15/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
28,OS-7268,FECHAMENTO O.S. À PRAZO,16/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
29,OS-7267,FECHAMENTO O.S. À PRAZO,16/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
30,OS-7274,FECHAMENTO O.S. À PRAZO,22/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
31,OS-6529,FECHAMENTO O.S. À PRAZO,23/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
32,OS-6531,FECHAMENTO O.S. À PRAZO,23/01/2024,"80,00 0,00 0,00","0,00",/ /,NaN,"80,00"
33,OS-7287,FECHAMENTO O.S. À PRAZO,24/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
34,OS-7288,FECHAMENTO O.S. À PRAZO,24/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
35,OS-7289,FECHAMENTO O.S. À PRAZO,24/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
36,OS-7286,FECHAMENTO O.S. À PRAZO,24/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
37,OS-7295,FECHAMENTO O.S. À PRAZO,26/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
38,NaN,NaN,SUBTOTAL:,"8.450,00 0,00 0,00","0,00",NaN,NaN,"8.450,00"

In [42]:
tabela.rename(columns=tabela.iloc[4], inplace = True)

tabela

,DOCTO:,HISTÓRICO,VENCIMENTO:,VALOR: R$ DESC.: R$ ACRESC:,VALOR REC: RECEBIDO EM:,NaN,NaN,R$ DEVIDO:
0,NaN,NaN,NaN,RDA DESIGN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,08/05/2024,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,EXTRATO DO CLIENTE,Período de: 01/01/2000,à,NaN,30/05/2024
3,ÓDIGO::,95 - CECILIA MASOUD,NaN,NaN,NaN,NaN,NaN,NaN
4,DOCTO:,HISTÓRICO,VENCIMENTO:,VALOR: R$ DESC.: R$ ACRESC:,VALOR REC: RECEBIDO EM:,NaN,NaN,R$ DEVIDO:
5,OS-7167,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
6,OS-7227,FECHAMENTO O.S. À PRAZO,08/01/2024,"100,00 0,00 0,00","0,00",/ /,NaN,"100,00"
7,OS-7055,FECHAMENTO O.S. À PRAZO,08/01/2024,"350,00 0,00 0,00","0,00",/ /,NaN,"350,00"
8,OS-7213,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
9,OS-7211,FECHAMENTO O.S. À PRAZO,08/01/2024,"80,00 0,00 0,00","0,00",/ /,NaN,"80,00"
10,OS-7209,FECHAMENTO O.S. À PRAZO,08/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
11,OS-7166,FECHAMENTO O.S. À PRAZO,08/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
12,OS-7168,FECHAMENTO O.S. À PRAZO,08/01/2024,"300,00 0,00 0,00","0,00",/ /,NaN,"300,00"
13,OS-7142,FECHAMENTO O.S. À PRAZO,08/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
14,OS-7222,FECHAMENTO O.S. À PRAZO,08/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
15,OS-7117,FECHAMENTO O.S. À PRAZO,08/01/2024,"400,00 0,00 0,00","0,00",/ /,NaN,"400,00"
16,OS-7141,FECHAMENTO O.S. À PRAZO,08/01/2024,"2.800,00 0,00 0,00","0,00",/ /,NaN,"2.800,00"
17,OS-7188,FECHAMENTO O.S. À PRAZO,08/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
18,OS-7054,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
19,OS-7092,FECHAMENTO O.S. À PRAZO,10/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
20,OS-7116,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
21,OS-7118,FECHAMENTO O.S. À PRAZO,10/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
22,OS-7119,FECHAMENTO O.S. À PRAZO,10/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
23,OS-7134,FECHAMENTO O.S. À PRAZO,10/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
24,OS-7135,FECHAMENTO O.S. À PRAZO,10/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
25,OS-7255,FECHAMENTO O.S. À PRAZO,15/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
26,OS-7254,FECHAMENTO O.S. À PRAZO,15/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
27,OS-7260,FECHAMENTO O.S. À PRAZO,15/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
28,OS-7268,FECHAMENTO O.S. À PRAZO,16/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
29,OS-7267,FECHAMENTO O.S. À PRAZO,16/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
30,OS-7274,FECHAMENTO O.S. À PRAZO,22/01/2024,"50,00 0,00 0,00","0,00",/ /,NaN,"50,00"
31,OS-6529,FECHAMENTO O.S. À PRAZO,23/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
32,OS-6531,FECHAMENTO O.S. À PRAZO,23/01/2024,"80,00 0,00 0,00","0,00",/ /,NaN,"80,00"
33,OS-7287,FECHAMENTO O.S. À PRAZO,24/01/2024,"200,00 0,00 0,00","0,00",/ /,NaN,"200,00"
34,OS-7288,FECHAMENTO O.S. À PRAZO,24/01/2024,"150,00 0,00 0,00","0,00",/ /,NaN,"150,00"
35,OS-7289,FECHAMENTO O.S. À PRAZO,24/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
36,OS-7286,FECHAMENTO O.S. À PRAZO,24/01/2024,"250,00 0,00 0,00","0,00",/ /,NaN,"250,00"
37,OS-7295,FECHAMENTO O.S. À PRAZO,26/01/2024,"60,00 0,00 0,00","0,00",/ /,NaN,"60,00"
38,NaN,NaN,SUBTOTAL:,"8.450,00 0,00 0,00","0,00",NaN,NaN,"8.450,00"

In [43]:
tabela = tabela[['DOCTO:', 'VENCIMENTO:', 'R$ DEVIDO:']]

tabela

     DOCTO:  VENCIMENTO:  R$ DEVIDO:
0       NaN          NaN         NaN
1       NaN          NaN         NaN
2       NaN          NaN  30/05/2024
3   ÓDIGO::          NaN         NaN
4    DOCTO:  VENCIMENTO:  R$ DEVIDO:
5   OS-7167   08/01/2024      250,00
6   OS-7227   08/01/2024      100,00
7   OS-7055   08/01/2024      350,00
8   OS-7213   08/01/2024      250,00
9   OS-7211   08/01/2024       80,00
10  OS-7209   08/01/2024       50,00
11  OS-7166   08/01/2024       50,00
12  OS-7168   08/01/2024      300,00
13  OS-7142   08/01/2024      200,00
14  OS-7222   08/01/2024      150,00
15  OS-7117   08/01/2024      400,00
16  OS-7141   08/01/2024    2.800,00
17  OS-7188   08/01/2024      250,00
18  OS-7054   10/01/2024      150,00
19  OS-7092   10/01/2024      200,00
20  OS-7116   10/01/2024      150,00
21  OS-7118   10/01/2024      200,00
22  OS-7119   10/01/2024      150,00
23  OS-7134   10/01/2024      250,00
24  OS-7135   10/01/2024      250,00
25  OS-7255   15/01/2024      250,00
26  OS-7254   15/01/2024      150,00
27  OS-7260   15/01/2024      250,00
28  OS-7268   16/01/2024       60,00
29  OS-7267   16/01/2024       60,00
30  OS-7274   22/01/2024       50,00
31  OS-6529   23/01/2024       60,00
32  OS-6531   23/01/2024       80,00
33  OS-7287   24/01/2024      200,00
34  OS-7288   24/01/2024      150,00
35  OS-7289   24/01/2024      250,00
36  OS-7286   24/01/2024      250,00
37  OS-7295   26/01/2024       60,00
38      NaN    SUBTOTAL:    8.450,00

In [44]:
tabela = tabela.drop(0)
tabela = tabela.drop(1)
tabela = tabela.drop(2)
tabela = tabela.drop(3)
tabela = tabela.drop(4)

tabela

     DOCTO: VENCIMENTO: R$ DEVIDO:
5   OS-7167  08/01/2024     250,00
6   OS-7227  08/01/2024     100,00
7   OS-7055  08/01/2024     350,00
8   OS-7213  08/01/2024     250,00
9   OS-7211  08/01/2024      80,00
10  OS-7209  08/01/2024      50,00
11  OS-7166  08/01/2024      50,00
12  OS-7168  08/01/2024     300,00
13  OS-7142  08/01/2024     200,00
14  OS-7222  08/01/2024     150,00
15  OS-7117  08/01/2024     400,00
16  OS-7141  08/01/2024   2.800,00
17  OS-7188  08/01/2024     250,00
18  OS-7054  10/01/2024     150,00
19  OS-7092  10/01/2024     200,00
20  OS-7116  10/01/2024     150,00
21  OS-7118  10/01/2024     200,00
22  OS-7119  10/01/2024     150,00
23  OS-7134  10/01/2024     250,00
24  OS-7135  10/01/2024     250,00
25  OS-7255  15/01/2024     250,00
26  OS-7254  15/01/2024     150,00
27  OS-7260  15/01/2024     250,00
28  OS-7268  16/01/2024      60,00
29  OS-7267  16/01/2024      60,00
30  OS-7274  22/01/2024      50,00
31  OS-6529  23/01/2024      60,00
32  OS-6531  23/01/2024      80,00
33  OS-7287  24/01/2024     200,00
34  OS-7288  24/01/2024     150,00
35  OS-7289  24/01/2024     250,00
36  OS-7286  24/01/2024     250,00
37  OS-7295  26/01/2024      60,00
38      NaN   SUBTOTAL:   8.450,00

In [45]:
import pandas

In [ ]:
preco = tabela["R$ DEVIDO:"]

preco

In [53]:
os = tabela.iloc[0,0]
preco = tabela.iloc[0,2]

print(os)
print(preco)

OS-7167
250,00